### ISSUE TITLE
colcon build fails to build builtin_interfaces for Android toolchain on arm64-v8a

### ISSUE THREAD

**Issue by mpconte** [ros2/rcl_interfaces#149]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10 (Ubuntu WSL subsystem)
- Installation type:
  - build from source
- Version or commit hash:
  - humble
- Client library (if applicable):
  - builtin_interfaces

#### Steps to reproduce issue
When building builtin_interfaces using colcon when installing from source with the following repos:

```
repositories:
  ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: humble
  ament_cmake_ros:
    type: git
    url: https://github.com/ros2/ament_cmake_ros.git
    version: humble
  ament_index:
    type: git
    url: https://github.com/ament/ament_index.git
    version: humble
  ament_lint:
    type: git
    url: https://github.com/ament/ament_lint.git
    version: humble
  ament_package:
    type: git
    url: https://github.com/ament/ament_package.git
    version: humble
  common_interfaces:
    type: git
    url: https://github.com/ros2/common_interfaces.git
    version: humble
  cyclonedds:
    type: git
    url: https://github.com/eclipse-cyclonedds/cyclonedds.git
    version: releases/0.10.x
  libstatistics_collector:
    type: git
    url: https://github.com/ros-tooling/libstatistics_collector.git
    version: humble
  libyaml_vendor:
    type: git
    url: https://github.com/ros2/libyaml_vendor.git
    version: humble
  mimick_vendor:
    type: git
    url: https://github.com/ros2/mimick_vendor.git
    version: humble
  osrf_testing_tools_cpp:
    type: git
    url: https://github.com/osrf/osrf_testing_tools_cpp.git
    version: master
  rcl:
    type: git
    url: https://github.com/ros2/rcl.git
    version: humble
  rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: humble
  rcl_logging:
    type: git
    url: https://github.com/ros2/rcl_logging.git
    version: humble
  rclcpp:
    type: git
    url: https://github.com/ros2/rclcpp.git
    version: humble
  rcpputils:
    type: git
    url: https://github.com/ros2/rcpputils.git
    version: humble
  rcutils:
    type: git
    url: https://github.com/ros2/rcutils.git
    version: humble
  rmw:
    type: git
    url: https://github.com/ros2/rmw.git
    version: humble
  rmw_cyclonedds:
    type: git
    url: https://github.com/ros2/rmw_cyclonedds.git
    version: humble
  rmw_dds_common:
    type: git
    url: https://github.com/ros2/rmw_dds_common.git
    version: humble
  rmw_implementation:
    type: git
    url: https://github.com/ros2/rmw_implementation.git
    version: humble
  ros2_tracing:
    type: git
    url: https://github.com/ros2/ros2_tracing.git
    version: humble
  rosidl:
    type: git
    url: https://github.com/ros2/rosidl.git
    version: humble
  rosidl_defaults:
    type: git
    url: https://github.com/ros2/rosidl_defaults.git
    version: humble
  rosidl_typesupport:
    type: git
    url: https://github.com/ros2/rosidl_typesupport.git
    version: humble
  test_interface_files:
    type: git
    url: https://github.com/ros2/test_interface_files.git
    version: humble
  unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: humble
# Hand made
  rcl_logging_android:
    type: git
    url: https://github.com/sloretz/rcl_logging_android.git
    version: main
```

And then running the following colcon command (specifying Android toolchain for arm64-v8a arch abi):

`colcon build --cmake-args -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=30 -DANDROID_NATIVE_API_LEVEL=30 -DCMAKE_ANDROID_NDK=/mnt/d/android-sdk/ndk/25.1.8937393 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_PLATFORM=30 -DCMAKE_TOOLCHAIN_FILE=/mnt/d/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake -DCMAKE_FIND_ROOT_PATH="/mnt/d/ros2-humble/install/ament_cmake_core/share/ament_cmake_core;/mnt/d/ros2-humble/install/ament_cmake_python/share/ament_cmake_python/cmake;/mnt/d/ros2-humble/install/osrf_testing_tools_cpp/share/osrf_testing_tools_cpp/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_dependencies/share/ament_cmake_export_dependencies/cmake;/mnt/d/ros2-humble/install/ament_cmake_test/share/ament_cmake_test/cmake;/mnt/d/ros2-humble/install/ament_cmake_lint_cmake/share/ament_cmake_lint_cmake/cmake;/mnt/d/ros2-humble/install/ament_cmake_gtest/share/ament_cmake_gtest/cmake;/mnt/d/ros2-humble/install/ament_cmake_copyright/share/ament_cmake_copyright/cmake;/mnt/d/ros2-humble/install/ament_cmake/share/ament_cmake/cmake;/mnt/d/ros2-humble/install/ament_cmake_libraries/share/ament_cmake_libraries/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_definitions/share/ament_cmake_export_definitions/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_include_directories/share/ament_cmake_export_include_directories/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_interfaces/share/ament_cmake_export_interfaces/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_libraries/share/ament_cmake_export_libraries/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_link_flags/share/ament_cmake_export_link_flags/cmake;/mnt/d/ros2-humble/install/ament_cmake_export_targets/share/ament_cmake_export_targets/cmake;/mnt/d/ros2-humble/install/ament_cmake_gen_version_h/share/ament_cmake_gen_version_h/cmake;/mnt/d/ros2-humble/install/ament_cmake_target_dependencies/share/ament_cmake_target_dependencies/cmake;/mnt/d/ros2-humble/install/ament_cmake_include_directories/share/ament_cmake_include_directories/cmake;/mnt/d/ros2-humble/install/ament_cmake_version/share/ament_cmake_version/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_core/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_python/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_test/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_dependencies/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_gtest/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_lint_cmake/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_copyright/cmake;/mnt/d/ros2-humble/install/share/ament_cmake/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_libraries/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_definitions/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_include_directories/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_interfaces/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_libraries/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_link_flags/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_export_targets/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_gen_version_h/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_target_dependencies/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_include_directories/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_version/cmake;/mnt/d/ros2-humble/install/share/ament_lint_auto/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_pytest/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_ros/cmake;/mnt/d/ros2-humble/install/share/ament_cmake_gmock/cmake;/mnt/d/performance_test_fixture/build/ament_cmake_core;/mnt/d/performance_test_fixture/build/ament_cmake_export_targets;/mnt/d/ros2-humble/install/share/rcutils/cmake;/mnt/d/ros2-humble/install/share/rosidl_typesupport_interface/cmake;/mnt/d/ros2-humble/install/share/rosidl_runtime_c/cmake;/mnt/d/ros2-humble/install/share/rcl_logging_interface/cmake;/mnt/d/ros2-humble/install/share/rcpputils/cmake;/mnt/d/ros2-humble/install/share/rosidl_runtime_cpp/cmake;/mnt/d/ros2-humble/install/share/rmw/cmake;/mnt/d/ros2-humble/install/share/rosidl_typesupport_c/cmake;/mnt/d/ros2-humble/install/share/rosidl_default_generators/cmake;/mnt/d/ros2-humble/install/share/rosidl_cmake/cmake;/mnt/d/ros2-humble/install/share/rosidl_adapter/cmake;/mnt/d/ros2-humble/install/share/rosidl_generator_c/cmake" -DBUILD_TESTING=OFF --merge-install --cmake-clean-cache --cmake-clean-first --packages-skip-build-finished --packages-skip mimick_vendor rcl_logging_spdlog --packages-up-to builtin_interfaces`

#### Expected behavior

I was expecting the builtin_interfaces library to successfully build

#### Actual behavior
```

/mnt/d/ros2-humble/build/builtin_interfaces/rosidl_typesupport_c/builtin_interfaces/msg/duration__type_support.cpp:10:10: /mnt/d/ros2-humble/build/builtin_interfaces/rosidl_typesupport_c/builtin_interfaces/msg/time__type_support.cpp:10:10: fatal error: fatal error: 'builtin_interfaces/msg/detail/time__rosidl_typesupport_introspection_c.h' file not found'builtin_interfaces/msg/detail/duration__rosidl_typesupport_introspection_c.h' file not found

#include "builtin_interfaces/msg/detail/duration__rosidl_typesupport_introspection_c.h"#include "builtin_interfaces/msg/detail/time__rosidl_typesupport_introspection_c.h"

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.
1 error generated.
make[2]: *** [CMakeFiles/builtin_interfaces__rosidl_typesupport_c.dir/build.make:90: CMakeFiles/builtin_interfaces__rosidl_typesupport_c.dir/rosidl_typesupport_c/builtin_interfaces/msg/duration__type_support.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/builtin_interfaces__rosidl_typesupport_c.dir/build.make:104: CMakeFiles/builtin_interfaces__rosidl_typesupport_c.dir/rosidl_typesupport_c/builtin_interfaces/msg/time__type_support.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:194: CMakeFiles/builtin_interfaces__rosidl_typesupport_c.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< builtin_interfaces [12min 48s, exited with code 2]

Summary: 0 packages finished [12min 52s]
  1 package failed: builtin_interfaces
  1 package had stderr output: builtin_interfaces
```
