### ISSUE TITLE
action_msgs is missing dependency on service_msgs

### ISSUE THREAD

**Issue by christianrauch** [ros2/rcl_interfaces#167]
## Bug report

I am trying to build a workspace from scratch:
```yaml
repositories:
  ament/ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: 2.5.2
  ament/ament_index:
    type: git
    url: https://github.com/ament/ament_index.git
    version: 1.8.1
  ament/ament_lint:
    type: git
    url: https://github.com/ament/ament_lint.git
    version: 0.17.1
  ament/ament_package:
    type: git
    url: https://github.com/ament/ament_package.git
    version: 0.16.3

  ros2/ament_cmake_ros:
    type: git
    url: https://github.com/ros2/ament_cmake_ros.git
    version: 0.12.0
  ros2/rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: 2.0.2
  ros2/rcutils:
    type: git
    url: https://github.com/ros2/rcutils.git
    version: 6.7.1
  ros2/rosidl:
    type: git
    url: https://github.com/ros2/rosidl.git
    version: 4.6.3
  ros2/rosidl_core:
    type: git
    url: https://github.com/ros2/rosidl_core.git
    version: 0.2.0
  ros2/rosidl_defaults:
    type: git
    url: https://github.com/ros2/rosidl_defaults.git
    version: 1.6.0
  ros2/unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: 2.5.0
```

Running `colcon build` will fail with:
```
--- stderr: action_msgs                                                                                                                                         
CMake Error at [...]/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:178 (message):
  Unable to generate service interface for 'srv/CancelGoal.srv'.  In order to
  generate service interfaces you must add a depend tag for 'service_msgs' in
  your package.xml.
Call Stack (most recent call first):
  CMakeLists.txt:30 (rosidl_generate_interfaces)
```

But `<depend>service_msgs</depend>` is already listed in the `package.xml`.

**Required Info:**

- Operating System:
  - Ubuntu
- Installation type:
  - source
- Version or commit hash:
  - 2.0.2 / jazzy

#### Steps to reproduce issue
See above.
